# Generated by Django 4.0.5 on 2022-06-30 23:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='createdAt',
        ),
        migrations.AddField(
            model_name='api',
            name='created_app',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
