# Generated by Django 4.0.5 on 2022-06-30 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_manager', '0002_remove_api_createdat_api_created_app'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='baseRoute',
            new_name='base_route',
        ),
        migrations.RenameField(
            model_name='api',
            old_name='created_app',
            new_name='created_at',
        ),
    ]
