# Generated by Django 4.0.5 on 2022-06-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_manager', '0003_rename_baseroute_api_base_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
