# Generated by Django 4.0.5 on 2022-06-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_manager', '0004_api_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
