# Generated by Django 4.0.5 on 2022-06-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_manager', '0007_alter_api_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
