# Generated by Django 4.0.5 on 2022-06-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_manager', '0009_endpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='metodo_http',
            field=models.IntegerField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')]),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='tipo_retorno',
            field=models.IntegerField(choices=[('JSON', 'JSON'), ('XML', 'XML')]),
        ),
    ]
