# Generated by Django 4.0.5 on 2022-07-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_manager', '0010_alter_endpoint_metodo_http_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoint',
            name='tipo_retorno',
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='metodo_http',
            field=models.IntegerField(choices=[('GET', 'Get')]),
        ),
    ]
