# Generated by Django 4.0.5 on 2022-07-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_manager', '0011_remove_endpoint_tipo_retorno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='metodo_http',
            field=models.IntegerField(choices=[('GET', 'GET')]),
        ),
    ]
