# Generated by Django 4.0.5 on 2022-07-01 00:13

from django.db import migrations, models
import endpoint_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_manager', '0013_endpoint_tipo_retorno_alter_endpoint_metodo_http'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='metodo_http',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', endpoint_manager.models.MetodosRequisicao['PATCH'])], default='GET', max_length=10),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='tipo_retorno',
            field=models.CharField(choices=[('JSON', 'JSON'), ('XML', 'XML')], default='JSON', max_length=10),
        ),
    ]
