# Generated by Django 4.0.5 on 2022-07-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_manager', '0014_alter_endpoint_metodo_http_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='metodo_http',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], default='GET', max_length=10),
        ),
    ]
