# Generated by Django 4.0.5 on 2022-07-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_manager', '0015_alter_endpoint_metodo_http'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='endpoint',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='status_code',
            field=models.IntegerField(default=200),
        ),
    ]
