# Generated by Django 4.0.5 on 2022-07-01 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_manager', '0016_endpoint_endpoint_endpoint_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='endpoint',
            field=models.CharField(default='', max_length=120, unique=True),
        ),
    ]
